{% set version = "2.6.8" %}

package:
  name: numexpr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numexpr/numexpr-{{ version }}.tar.gz
  sha256: ee8bc7201aa2f1962c67d27c326a11eef9df887d7b87b1278a1d4e722bf44375
  patches:
    # seems to trip up py37 on windows only?
    - 0001-remove-line-continuation-characters-in-cpuinfo.patch

build:
  number: 0
  skip: True  # [blas_impl == 'openblas' and win]
  script:
    - cp $PREFIX/site.cfg site.cfg  # [unix]
    - copy %PREFIX%\\site.cfg site.cfg  # [win]
    - dos2unix numexpr/*.py  # [win]
    - dos2unix numexpr/tests/*.py  # [win]
    - {{PYTHON}} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - nomkl  # [x86 and blas_impl == 'openblas']
    - numpy 1.11.*
    - python
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - setuptools
    - nomkl  # [x86 and blas_impl == 'openblas']
  imports:
    - numexpr
    - numexpr.interpreter

about:
  home: https://github.com/pydata/numexpr
  license: MIT
  license_file: LICENSE.txt
  summary: 'Fast numerical expression evaluator for NumPy.'
  description: |
    Numexpr is a fast numerical expression evaluator for NumPy. With it,
    expressions that operate on arrays (like "3*a+4*b") are accelerated and use
    less memory than doing the same calculation in Python.
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  dev_url: https://github.com/pydata/numexpr

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - scopatz
    - djkirkham
