{% set name = "numexpr" %}
{% set version = "2.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75b2c01a4eda2e7c357bc67a3f5c3dd76506c15b5fd4dc42845ef2e182181bad

build:
  number: 0
  skip: true  # [blas_impl == 'openblas' and win]
  skip: true  # [py<310]
  script:
    - sed -i.bak 's/^license = "MIT"/license = { text = "MIT" }/' pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl' and x86]
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas' and x86]
    - numpy {{ numpy}}
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.23.0

test:
  # imports are included to run_test.py
  requires:
    - nomkl  # [x86 and blas_impl == 'openblas']
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://github.com/pydata/numexpr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy
  description: |
    Numexpr is a fast numerical expression evaluator for NumPy. With it,
    expressions that operate on arrays (like "3*a+4*b") are accelerated and use
    less memory than doing the same calculation in Python.
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  dev_url: https://github.com/pydata/numexpr

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - scopatz
    - djkirkham
