travis:
  secure:
    BINSTAR_TOKEN: atqof0UMqV5AuEqeoFq4ReXi7r4ytd9l2oNFSf3CC1UkUCSCgIfU7BIYGqHBr18NWQnho3CB7na8dfW8401uGfmaGK5MaM73twDQYCtAY0tYYff/oSzfZrpx9J00HmcAMOrqCPrar7lWnJLPFciM0cBZsHuEN7mAv7zWrmeEWOD2HExj5adfjQ7Mcs4UrfOpgW9HqF8FcvumPw95MYzyHCCRLwNRNgp3bdNJ6K7EdGEdLY6YJLIVHxuYMntIn5W905/eaVrijKH+iHJVjwFyu9MoqzaNtQF8QpTMXFXfwOmS85oNnlPTf90XMb4k/3M96l9UTPj20DaOhXUtxKPrIiXqI2vYhw/iHNQXGDAPGpjq36NaKc3y5hP2yfNXt+p9brAC+X2Q8koKAbsrzDWnlAGvV3wZuAj82Bd2OfOSmO/6cxfjxirKf2WG+oVelK1jZTZciMx9u4M1rxHzsRa3GT5L4eJAiwZr5nnK66T4rTaGsdpS9dfQoGOfN0DAJv9HovQdEsNWRGxI7zNduZaqHtxtnlN98OfbILRrRfj5VdK7eZ4zXMbFq2Dquu1n++iQGWuBGH2rZIyVwpUtIJbSDj5WFnSkoaupPU0yr2X3FepZFvZPIx/+v0LmtGhRMhN59ZfwrY3K3cLPkvasarbcn3qRR8Nr1TPhhs6KG1GGMxU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
